# Generated by Django 6.0.5 on 2026-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.IntegerField()),
                ('role', models.IntegerField()),
                ('event_name', models.CharField(max_length=256)),
                ('theme', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('event_addr', models.CharField(max_length=80)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('ID', 'date')},
            },
        ),
    ]
