# Generated by Django 6.0.5 on 2026-05-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='hash',
        ),
    ]
