# Generated by Django 6.0.5 on 2026-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_assistant_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='event_addr',
            field=models.CharField(max_length=256),
        ),
    ]
