# Generated by Django 6.0.5 on 2026-06-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_assistant_event_addr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assistant',
            new_name='Attendee',
        ),
    ]
