# Generated by Django 6.0.5 on 2026-06-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_rename_assistant_attendee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendee',
            new_name='Post_attendee',
        ),
    ]
