# Generated by Django 6.0.5 on 2026-06-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_rename_attendee_post_attendee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_attendee',
            new_name='Post',
        ),
    ]
