# Generated by Django 6.0.5 on 2026-06-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_post_attendee_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_type',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
