# Generated by Django 6.0.5 on 2026-06-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_post_event_type_alter_post_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.IntegerField(),
        ),
    ]
