# Generated by Django 6.0.5 on 2026-06-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_post_event_type_alter_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
