# Generated by Django 6.0.5 on 2026-06-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_post_email_post_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.TextField(),
        ),
    ]
