# Generated by Django 6.0.5 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_post_event_type_alter_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qr_hash',
            field=models.CharField(default='TestHash', max_length=256),
            preserve_default=False,
        ),
    ]
